# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fraise < Formula
  desc "In-memory temporal graph database for AI agents memory"
  homepage "https://github.com/FraiseHQ/fraise"
  version "0.1.0-rc.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FraiseHQ/fraise/releases/download/v0.1.0-rc.4/fraise_0.1.0-rc.4_darwin_amd64.tar.gz"
      sha256 "6097eba19fa34677a2cc7f55e67484668cfb72a367c74d225acbbe24eb80a075"

      define_method(:install) do
        bin.install "fraise"
        (etc/"fraise").install "fraise.config.toml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FraiseHQ/fraise/releases/download/v0.1.0-rc.4/fraise_0.1.0-rc.4_darwin_arm64.tar.gz"
      sha256 "5e4fa65ff87e7a5bb53377aca0d58e6196e1b89d1a2f1c8ec7fb147f45823ba1"

      define_method(:install) do
        bin.install "fraise"
        (etc/"fraise").install "fraise.config.toml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FraiseHQ/fraise/releases/download/v0.1.0-rc.4/fraise_0.1.0-rc.4_linux_amd64.tar.gz"
      sha256 "1cffeb10e6e9d5ad8b8ad3878d68d3fec3b46269b47e3b39eaefcbdfd9ab8d1b"
      define_method(:install) do
        bin.install "fraise"
        (etc/"fraise").install "fraise.config.toml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FraiseHQ/fraise/releases/download/v0.1.0-rc.4/fraise_0.1.0-rc.4_linux_arm64.tar.gz"
      sha256 "68ad1b90d2583185afcdab5fefa834950d251a1151672d2a6d8af02730713ac3"
      define_method(:install) do
        bin.install "fraise"
        (etc/"fraise").install "fraise.config.toml"
      end
    end
  end

  def caveats
    <<~EOS
      Run fraise as a supervised background service:
        brew services start fraise
      Config:  #{etc}/fraise/fraise.config.toml
      Logs:    #{var}/log/fraise.log
    EOS
  end

  service do
    run [opt_bin/"fraise", "-config", etc/"fraise/fraise.config.toml"]
    keep_alive true
    log_path var/"log/fraise.log"
    error_log_path var/"log/fraise.log"
    working_dir var
  end

  test do
    assert_match "-config", shell_output("#{bin}/fraise -h 2>&1")
  end
end
