# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fraise < Formula
  desc "In-memory temporal graph database for AI agents memory"
  homepage "https://github.com/FraiseHQ/fraise"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FraiseHQ/fraise/releases/download/v0.2.1/fraise_0.2.1_darwin_amd64.tar.gz"
      sha256 "f92cdb1739d9c2f55c6e95abdb84a79a5ee02c9f0acc51c53c09757e80e0e4b3"

      define_method(:install) do
        bin.install "fraise"
        (etc/"fraise").install "fraise.config.toml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FraiseHQ/fraise/releases/download/v0.2.1/fraise_0.2.1_darwin_arm64.tar.gz"
      sha256 "9571cfcf7a207e54f9e7f60692340eda89a8def736c5fefb7de5153cbd68959d"

      define_method(:install) do
        bin.install "fraise"
        (etc/"fraise").install "fraise.config.toml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FraiseHQ/fraise/releases/download/v0.2.1/fraise_0.2.1_linux_amd64.tar.gz"
      sha256 "43127094868fba434f1a1c0a40a762766977a5bbf1a2c09993b37aba8d85e58b"
      define_method(:install) do
        bin.install "fraise"
        (etc/"fraise").install "fraise.config.toml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FraiseHQ/fraise/releases/download/v0.2.1/fraise_0.2.1_linux_arm64.tar.gz"
      sha256 "d0d3260eadad9999f07af6e87bb870f8bb4d7d8281286dae14862083571aad27"
      define_method(:install) do
        bin.install "fraise"
        (etc/"fraise").install "fraise.config.toml"
      end
    end
  end

  def caveats
    <<~EOS
      Run fraise as a supervised background service:
        brew services start fraise
      Config:  #{etc}/fraise/fraise.config.toml
      Logs:    #{var}/log/fraise.log
    EOS
  end

  service do
    run [opt_bin/"fraise", "-config", etc/"fraise/fraise.config.toml"]
    keep_alive true
    log_path var/"log/fraise.log"
    error_log_path var/"log/fraise.log"
    working_dir var
  end

  test do
    assert_match "-config", shell_output("#{bin}/fraise -h 2>&1")
  end
end
